In [24]:
# Check TF version

In [25]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [26]:
# Hello TensorFlow!

In [27]:
hello=tf.constant("Hello, HJ!")

In [28]:
print(hello)

tf.Tensor(b'Hello, HJ!', shape=(), dtype=string)


In [29]:
# Tensors

In [30]:
tf1 = tf.constant(3)
tf2 = tf.constant([1. ,2., 3.])
tf3 = tf.constant([[1., 2., 3.], [4., 5., 6.]])
tf4 = tf.constant([[[1., 2., 3.]], [[7., 8., 9.]]])

In [31]:
print(tf1)
print(tf2)
print(tf3)
print(tf4)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[1. 2. 3.]]

 [[7. 8. 9.]]], shape=(2, 1, 3), dtype=float32)


In [32]:
# Computational Graph

In [33]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0, tf.float32)

In [36]:
print(node1)
print(node2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


In [34]:
@tf.function # 이 줄 없어도 실행은 됨
def add():
    return node1 + node2

In [35]:
output = add()
print(output)

tf.Tensor(7.0, shape=(), dtype=float32)
