In [1]:
# Learning rate and Evaluation
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [12]:
# try different learning_rate
# learning_rate = 3939  # it works too hahaha
# learning_rate = 0.1
learning_rate = 1e-10  # small learning rate won't work either

In [13]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=3, input_dim=3, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=learning_rate), metrics=['accuracy'])

tf.model.fit(x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 2/1000
1/1 [==============================] - 0s 998us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 5/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 9/1000
1/1 [==============================] - 0s 991us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 11/1000
1

Epoch 165/1000
1/1 [==============================] - 0s 997us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 166/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 167/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 168/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 169/1000
1/1 [==============================] - 0s 993us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 170/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 171/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 172/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 173/1000
1/1 [==============================] - 0s 955us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 174/1000
1/1 [==============================] - 0s 998us/step - loss: 3.7109 - accuracy:

1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 328/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 329/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 330/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 331/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 332/1000
1/1 [==============================] - 0s 997us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 333/1000
1/1 [==============================] - 0s 997us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 334/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 335/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 336/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 337/1

1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 490/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 491/1000
1/1 [==============================] - 0s 997us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 492/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 493/1000
1/1 [==============================] - 0s 5ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 494/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 495/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 496/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 497/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 498/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 499/100

1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 652/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 653/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 654/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 655/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 656/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 657/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 658/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 659/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 660/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 661/1000


1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 814/1000
1/1 [==============================] - 0s 5ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 815/1000
1/1 [==============================] - 0s 5ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 816/1000
1/1 [==============================] - 0s 997us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 817/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 818/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 819/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 820/1000
1/1 [==============================] - 0s 997us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 821/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 822/1000
1/1 [==============================] - 0s 998us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 823

1/1 [==============================] - 0s 1ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 976/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 977/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 978/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 979/1000
1/1 [==============================] - 0s 1000us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 980/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 981/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 982/1000
1/1 [==============================] - 0s 824us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 983/1000
1/1 [==============================] - 0s 4ms/step - loss: 3.7109 - accuracy: 0.3750
Epoch 984/1000
1/1 [==============================] - 0s 934us/step - loss: 3.7109 - accuracy: 0.3750
Epoch 98

In [14]:
# predict
print("Prediction: ", tf.model.predict_classes(x_test))

# Calculate the accuracy
print("Accuracy: ", tf.model.evaluate(x_test, y_test)[1])

Prediction:  [1 1 1]
1/1 [==============================] - 0s 2ms/step - loss: 2.7786 - accuracy: 0.0000e+00
Accuracy:  0.0


In [10]:
'''
Result
LR = 3939 : Accuracy = 1.0
LR = 0.1 : Accuracy = 1.0
LR = 1e-10: Accuracy = 0.0
'''

'\nResult\nLR = 3939 : Accuracy = 1.0\nLR = 0.1 : Accuracy = 1.0\nLR = 1e-10: \n\n'

In [15]:
# linear regression without min & max
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [18]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=100)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 233299230720.0000
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 256321345826961551291056128.0000
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: inf
Epoch 4/100
1/1 [==============================] - 0s 997us/step - loss: inf
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: inf
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: inf
Epoch 7/100
1/1 [==========

1/1 [==============================] - 0s 997us/step - loss: nan
Epoch 100/100
1/1 [==============================] - 0s 2ms/step - loss: nan


In [19]:
print(history.history['loss']) # loss == nan

[233299230720.0, 2.5632134582696155e+26, inf, inf, inf, inf, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


In [2]:
# linear regression with min & max
import tensorflow as tf
import numpy as np

def min_max_scaler(data):
    numerator = data - np.min(data, 0) # axis=0: 세로로 한줄씩 봄
    denominator = np.max(data, 0) - np.min(data, 0) # axis=0: 세로로 한줄씩 봄
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

In [4]:
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [5]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [9]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=1000)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
1/1 [==============================] - 0s 998us/step - loss: 1.2787
Epoch 2/1000
1/1 [==============================] - 0s 997us/step - loss: 1.2786
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2785
Epoch 4/1000
1/1 [==============================] - 0s 961us/step - loss: 1.2784
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2783
Epoch 6/1000
1/1 [==============================] - 0s 980us/step - loss: 1.2782
Epoch 7/1000
1/1 [======================

Epoch 95/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2700
Epoch 96/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2699
Epoch 97/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2698
Epoch 98/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2697
Epoch 99/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2696
Epoch 100/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2695
Epoch 101/1000
1/1 [==============================] - 0s 5ms/step - loss: 1.2694
Epoch 102/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2693
Epoch 103/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2692
Epoch 104/1000
1/1 [==============================] - 0s 997us/step - loss: 1.2691
Epoch 105/1000
1/1 [==============================] - 0s 8ms/step - loss: 1.2691
Epoch 106/1000
1/1 [==============================] - 0s 998us/step - loss: 1.2690
Epoch 107/1000
1/1 [=========

Epoch 195/1000
1/1 [==============================] - 0s 4ms/step - loss: 1.2608
Epoch 196/1000
1/1 [==============================] - 0s 968us/step - loss: 1.2607
Epoch 197/1000
1/1 [==============================] - 0s 997us/step - loss: 1.2606
Epoch 198/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2605
Epoch 199/1000
1/1 [==============================] - 0s 997us/step - loss: 1.2604
Epoch 200/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2603
Epoch 201/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2602
Epoch 202/1000
1/1 [==============================] - 0s 998us/step - loss: 1.2601
Epoch 203/1000
1/1 [==============================] - 0s 417us/step - loss: 1.2600
Epoch 204/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2599
Epoch 205/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2599
Epoch 206/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2598
Epoch 207/1000
1/1

1/1 [==============================] - 0s 2ms/step - loss: 1.2426
Epoch 396/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2425
Epoch 397/1000
1/1 [==============================] - 0s 995us/step - loss: 1.2424
Epoch 398/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2423
Epoch 399/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2422
Epoch 400/1000
1/1 [==============================] - 0s 881us/step - loss: 1.2421
Epoch 401/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2420
Epoch 402/1000
1/1 [==============================] - 0s 481us/step - loss: 1.2419
Epoch 403/1000
1/1 [==============================] - 0s 956us/step - loss: 1.2418
Epoch 404/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2418
Epoch 405/1000
1/1 [==============================] - 0s 0s/step - loss: 1.2417
Epoch 406/1000
1/1 [==============================] - 0s 265us/step - loss: 1.2416
Epoch 407/1000
1/1 [==============

1/1 [==============================] - 0s 3ms/step - loss: 1.2246
Epoch 596/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2246
Epoch 597/1000
1/1 [==============================] - 0s 999us/step - loss: 1.2245
Epoch 598/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2244
Epoch 599/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2243
Epoch 600/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2242
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2241
Epoch 602/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2240
Epoch 603/1000
1/1 [==============================] - 0s 996us/step - loss: 1.2239
Epoch 604/1000
1/1 [==============================] - 0s 997us/step - loss: 1.2238
Epoch 605/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2238
Epoch 606/1000
1/1 [==============================] - 0s 986us/step - loss: 1.2237
Epoch 607/1000
1/1 [===============

1/1 [==============================] - 0s 997us/step - loss: 1.2070
Epoch 796/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2069
Epoch 797/1000
1/1 [==============================] - 0s 997us/step - loss: 1.2068
Epoch 798/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2067
Epoch 799/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2066
Epoch 800/1000
1/1 [==============================] - 0s 310us/step - loss: 1.2065
Epoch 801/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2065
Epoch 802/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2064
Epoch 803/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2063
Epoch 804/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.2062
Epoch 805/1000
1/1 [==============================] - 0s 997us/step - loss: 1.2061
Epoch 806/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.2060
Epoch 807/1000
1/1 [===============

1/1 [==============================] - 0s 339us/step - loss: 1.1896
Epoch 996/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.1895
Epoch 997/1000
1/1 [==============================] - 0s 997us/step - loss: 1.1894
Epoch 998/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.1893
Epoch 999/1000
1/1 [==============================] - 0s 997us/step - loss: 1.1892
Epoch 1000/1000
1/1 [==============================] - 0s 997us/step - loss: 1.1892


In [8]:
predictions = tf.model.predict(x_data)
score = tf.model.evaluate(x_data, y_data)

print('Prediction: \n', predictions)
print('Cost: ', score)

1/1 [==============================] - 0s 997us/step - loss: 0.0686
Prediction: 
 [[ 0.87025243]
 [ 0.45729607]
 [ 0.2910609 ]
 [ 0.13356379]
 [ 0.2532506 ]
 [ 0.34093443]
 [-0.13867307]
 [-0.00218759]]
Cost:  0.06863521784543991


In [22]:
# 직접 계산한 cost
print(tf.reduce_mean(tf.square(y_data-predictions)))

tf.Tensor(0.06863521270162445, shape=(), dtype=float64)


In [25]:
# MNIST data
import tensorflow as tf

mnist = tf.keras.datasets.mnist
print("mnist download complete")
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0
print("normalization done")

mnist download complete
11493376/11490434 [==============================] - 12s 1us/step
normalization done


In [26]:
#linear classifier
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)), #28 by 28 mnist input flatten
    tf.keras.layers.Dense(10,activation='softmax') # 10: units(출력값의 차원)
])

In [28]:
model.compile(optimizer='SGD',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 1s 741us/step - loss: 0.7760 - accuracy: 0.8126
Epoch 2/5
1875/1875 [==============================] - 1s 682us/step - loss: 0.4564 - accuracy: 0.8796
Epoch 3/5
1875/1875 [==============================] - 1s 706us/step - loss: 0.4032 - accuracy: 0.8911
Epoch 4/5
1875/1875 [==============================] - 1s 666us/step - loss: 0.3768 - accuracy: 0.8967
Epoch 5/5
1875/1875 [==============================] - 1s 698us/step - loss: 0.3600 - accuracy: 0.9006
313/313 - 0s - loss: 0.3358 - accuracy: 0.9103


[0.3357609212398529, 0.9103000164031982]