In [2]:
# Multi-variable linear regression
import tensorflow as tf
import numpy as np

In [38]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [39]:
tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3))  # input_dim=3 gives multi-variable regression
# tf.model.add(tf.keras.layers.Activation('linear'))  # this line can be omitted, as linear activation is default
# advanced reading https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()
history = tf.model.fit(x_data, y_data, epochs=100)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 73549.3750
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 23057.8555
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 7231.4414
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 2270.6997
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 715.7685
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 228.3783
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 75.6052
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 27.7168
Epoch 9/10

Epoch 98/100
1/1 [==============================] - 0s 2ms/step - loss: 5.5889
Epoch 99/100
1/1 [==============================] - 0s 994us/step - loss: 5.5860
Epoch 100/100
1/1 [==============================] - 0s 3ms/step - loss: 5.5831


In [12]:
y_predict = tf.model.predict(np.array([[72., 93., 90.]]))
print(y_predict)

[[176.27377]]


In [1]:
# Loading Data from file
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('csv/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]] # 이렇게 쓰는 게 맞음
y_data_2 = xy[:, -1] # 이렇게 쓰면 안 됨

In [3]:
print(xy, "\nxy shape:", xy.shape, "\n")
print(x_data, "\nx_data shape:", x_data.shape, "\n")
print(y_data, "\ny_data shape:", y_data.shape, "\n")
print(y_data_2, "\ny_data_2 shape:", y_data_2.shape, "\n")

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]] 
xy shape: (25, 4) 

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78. 

In [10]:
print(len(xy))
print(len(x_data))
print(len(y_data))

25
25
25


In [7]:
tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer

tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3)

# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2000
1/1 [==============================] - 0s 967us/step - loss: 27083.3047
Epoch 2/2000
1/1 [==============================] - 0s 916us/step - loss: 10030.7275
Epoch 3/2000
1/1 [==============================] - 0s 2ms/step - loss: 3725.9070
Epoch 4/2000
1/1 [==============================] - 0s 1ms/step - loss: 1394.8302
Epoch 5/2000
1/1 [==============================] - 0s 900us/step - loss: 532.9539
Epoch 6/2000
1/1 [==============================] - 0s 988us/step - loss: 214.2834
Epoch 7/2000
1/1 [==============================] - 0s 3ms/step - loss: 96.4502
Epoch 8/2000
1/1 [==============================] - 0s 998us/step - loss: 

1/1 [==============================] - 0s 998us/step - loss: 24.2115
Epoch 193/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1960
Epoch 194/2000
1/1 [==============================] - 0s 998us/step - loss: 24.1804
Epoch 195/2000
1/1 [==============================] - 0s 1ms/step - loss: 24.1649
Epoch 196/2000
1/1 [==============================] - 0s 996us/step - loss: 24.1494
Epoch 197/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.1339
Epoch 198/2000
1/1 [==============================] - 0s 998us/step - loss: 24.1183
Epoch 199/2000
1/1 [==============================] - 0s 997us/step - loss: 24.1029
Epoch 200/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.0874
Epoch 201/2000
1/1 [==============================] - 0s 951us/step - loss: 24.0720
Epoch 202/2000
1/1 [==============================] - 0s 998us/step - loss: 24.0565
Epoch 203/2000
1/1 [==============================] - 0s 2ms/step - loss: 24.0411
Epoch 204/2000
1/

Epoch 389/2000
1/1 [==============================] - 0s 3ms/step - loss: 21.3926
Epoch 390/2000
1/1 [==============================] - 0s 999us/step - loss: 21.3795
Epoch 391/2000
1/1 [==============================] - 0s 996us/step - loss: 21.3664
Epoch 392/2000
1/1 [==============================] - 0s 997us/step - loss: 21.3533
Epoch 393/2000
1/1 [==============================] - 0s 997us/step - loss: 21.3402
Epoch 394/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.3272
Epoch 395/2000
1/1 [==============================] - 0s 918us/step - loss: 21.3141
Epoch 396/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.3011
Epoch 397/2000
1/1 [==============================] - 0s 2ms/step - loss: 21.2881
Epoch 398/2000
1/1 [==============================] - 0s 996us/step - loss: 21.2750
Epoch 399/2000
1/1 [==============================] - 0s 996us/step - loss: 21.2620
Epoch 400/2000
1/1 [==============================] - 0s 998us/step - loss: 21.2490


1/1 [==============================] - 0s 1ms/step - loss: 19.0292
Epoch 586/2000
1/1 [==============================] - 0s 998us/step - loss: 19.0181
Epoch 587/2000
1/1 [==============================] - 0s 3ms/step - loss: 19.0071
Epoch 588/2000
1/1 [==============================] - 0s 996us/step - loss: 18.9961
Epoch 589/2000
1/1 [==============================] - 0s 917us/step - loss: 18.9850
Epoch 590/2000
1/1 [==============================] - 0s 5ms/step - loss: 18.9740
Epoch 591/2000
1/1 [==============================] - 0s 0s/step - loss: 18.9630
Epoch 592/2000
1/1 [==============================] - 0s 196us/step - loss: 18.9520
Epoch 593/2000
1/1 [==============================] - 0s 997us/step - loss: 18.9410
Epoch 594/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.9300
Epoch 595/2000
1/1 [==============================] - 0s 997us/step - loss: 18.9191
Epoch 596/2000
1/1 [==============================] - 0s 2ms/step - loss: 18.9081
Epoch 597/2000
1/1 [

Epoch 782/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.0267
Epoch 783/2000
1/1 [==============================] - 0s 997us/step - loss: 17.0174
Epoch 784/2000
1/1 [==============================] - 0s 998us/step - loss: 17.0081
Epoch 785/2000
1/1 [==============================] - 0s 997us/step - loss: 16.9988
Epoch 786/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.9895
Epoch 787/2000
1/1 [==============================] - 0s 999us/step - loss: 16.9803
Epoch 788/2000
1/1 [==============================] - 0s 999us/step - loss: 16.9710
Epoch 789/2000
1/1 [==============================] - 0s 1ms/step - loss: 16.9617
Epoch 790/2000
1/1 [==============================] - 0s 2ms/step - loss: 16.9525
Epoch 791/2000
1/1 [==============================] - 0s 997us/step - loss: 16.9432
Epoch 792/2000
1/1 [==============================] - 0s 3ms/step - loss: 16.9340
Epoch 793/2000
1/1 [==============================] - 0s 998us/step - loss: 16.9247
Ep

1/1 [==============================] - 0s 998us/step - loss: 15.3470
Epoch 979/2000
1/1 [==============================] - 0s 1ms/step - loss: 15.3391
Epoch 980/2000
1/1 [==============================] - 0s 997us/step - loss: 15.3313
Epoch 981/2000
1/1 [==============================] - 0s 998us/step - loss: 15.3234
Epoch 982/2000
1/1 [==============================] - 0s 997us/step - loss: 15.3156
Epoch 983/2000
1/1 [==============================] - 0s 1ms/step - loss: 15.3077
Epoch 984/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.2999
Epoch 985/2000
1/1 [==============================] - 0s 997us/step - loss: 15.2921
Epoch 986/2000
1/1 [==============================] - 0s 997us/step - loss: 15.2843
Epoch 987/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2765
Epoch 988/2000
1/1 [==============================] - 0s 5ms/step - loss: 15.2687
Epoch 989/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2609
Epoch 990/2000
1/1 

Epoch 1076/2000
1/1 [==============================] - 0s 933us/step - loss: 14.6082
Epoch 1077/2000
1/1 [==============================] - 0s 996us/step - loss: 14.6010
Epoch 1078/2000
1/1 [==============================] - 0s 999us/step - loss: 14.5938
Epoch 1079/2000
1/1 [==============================] - 0s 999us/step - loss: 14.5865
Epoch 1080/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.5794
Epoch 1081/2000
1/1 [==============================] - 0s 997us/step - loss: 14.5721
Epoch 1082/2000
1/1 [==============================] - 0s 998us/step - loss: 14.5650
Epoch 1083/2000
1/1 [==============================] - 0s 837us/step - loss: 14.5578
Epoch 1084/2000
1/1 [==============================] - 0s 996us/step - loss: 14.5506
Epoch 1085/2000
1/1 [==============================] - 0s 1ms/step - loss: 14.5434
Epoch 1086/2000
1/1 [==============================] - 0s 662us/step - loss: 14.5363
Epoch 1087/2000
1/1 [==============================] - 0s 947us/step 

1/1 [==============================] - 0s 1ms/step - loss: 13.3182
Epoch 1271/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.3121
Epoch 1272/2000
1/1 [==============================] - 0s 997us/step - loss: 13.3060
Epoch 1273/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.2999
Epoch 1274/2000
1/1 [==============================] - 0s 997us/step - loss: 13.2938
Epoch 1275/2000
1/1 [==============================] - 0s 997us/step - loss: 13.2877
Epoch 1276/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.2817
Epoch 1277/2000
1/1 [==============================] - 0s 714us/step - loss: 13.2756
Epoch 1278/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.2695
Epoch 1279/2000
1/1 [==============================] - 0s 997us/step - loss: 13.2634
Epoch 1280/2000
1/1 [==============================] - 0s 997us/step - loss: 13.2574
Epoch 1281/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.2513
Epoch 12

1/1 [==============================] - 0s 2ms/step - loss: 12.2273
Epoch 1465/2000
1/1 [==============================] - 0s 963us/step - loss: 12.2221
Epoch 1466/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.2169
Epoch 1467/2000
1/1 [==============================] - 0s 1ms/step - loss: 12.2118
Epoch 1468/2000
1/1 [==============================] - 0s 999us/step - loss: 12.2066
Epoch 1469/2000
1/1 [==============================] - 0s 937us/step - loss: 12.2015
Epoch 1470/2000
1/1 [==============================] - 0s 0s/step - loss: 12.1963
Epoch 1471/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1912
Epoch 1472/2000
1/1 [==============================] - 0s 668us/step - loss: 12.1861
Epoch 1473/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1809
Epoch 1474/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.1758
Epoch 1475/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1707
Epoch 1476/20

1/1 [==============================] - 0s 996us/step - loss: 11.3043
Epoch 1659/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.2999
Epoch 1660/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.2956
Epoch 1661/2000
1/1 [==============================] - 0s 998us/step - loss: 11.2912
Epoch 1662/2000
1/1 [==============================] - 0s 999us/step - loss: 11.2869
Epoch 1663/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.2825
Epoch 1664/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.2781
Epoch 1665/2000
1/1 [==============================] - 0s 993us/step - loss: 11.2738
Epoch 1666/2000
1/1 [==============================] - 0s 1ms/step - loss: 11.2695
Epoch 1667/2000
1/1 [==============================] - 0s 997us/step - loss: 11.2651
Epoch 1668/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.2608
Epoch 1669/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.2564
Epoch 1670

1/1 [==============================] - 0s 997us/step - loss: 10.5232
Epoch 1853/2000
1/1 [==============================] - 0s 997us/step - loss: 10.5195
Epoch 1854/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.5158
Epoch 1855/2000
1/1 [==============================] - 0s 998us/step - loss: 10.5121
Epoch 1856/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.5084
Epoch 1857/2000
1/1 [==============================] - 0s 692us/step - loss: 10.5047
Epoch 1858/2000
1/1 [==============================] - 0s 1ms/step - loss: 10.5010
Epoch 1859/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.4974
Epoch 1860/2000
1/1 [==============================] - 0s 1ms/step - loss: 10.4937
Epoch 1861/2000
1/1 [==============================] - 0s 1ms/step - loss: 10.4900
Epoch 1862/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.4864
Epoch 1863/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.4827
Epoch 1864/2

In [8]:
# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

Your score will be  [[181.78899]]
Other scores will be  [[166.939  ]
 [181.43803]]


In [19]:
# 이것들의 차이 알아두기
print(xy[-1])
print(xy[[-1]])
print(xy[-1:])

[ 96.  93.  95. 192.]
[[ 96.  93.  95. 192.]]
[[ 96.  93.  95. 192.]]
