In [30]:
# Lab 8은 TF2 코드 없어서 TF1 코드 + ppt 참고함
import tensorflow as tf
import numpy as np

In [159]:
# shape, rank, axis
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.ndim)
print(t.shape)
print(tf.shape(t))

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
tf.Tensor([7], shape=(1,), dtype=int32)


In [160]:
t = tf.constant([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.ndim)
print(t.shape)
print(tf.shape(t))
# 위 셀이랑 같음

tf.Tensor([0. 1. 2. 3. 4. 5. 6.], shape=(7,), dtype=float32)
1
(7,)
tf.Tensor([7], shape=(1,), dtype=int32)


In [192]:
t = tf.constant([[1,2],[3,4],[5,6]])
print(t)
print(t.ndim)
print(t.shape)
print(tf.shape(t)) # 여기서 shape=(rank, )인 듯
tf.shape(t)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
2
(3, 2)
tf.Tensor([3 2], shape=(2,), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [193]:
t # 여기서 shape: 진짜 shape임

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [181]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
# print(t)
print(t.ndim)
print(t.shape)
print(tf.shape(t)) 
tf.shape(t) 

4
(1, 2, 3, 4)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [182]:
print(t)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)


In [36]:
# matmul vs multiply (broadcasting)
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.],[2.]])
tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 5.],
       [11.]], dtype=float32)>

In [41]:
print(matrix1*matrix2)

tf.Tensor(
[[1. 2.]
 [6. 8.]], shape=(2, 2), dtype=float32)


In [48]:
# reduce mean & sum
tf.reduce_mean([1, 2], axis=0).numpy() # eval 대신 numpy 쓰라고 뜸(tf1/tf2 차이점인 듯)
tf.reduce_mean([1.0, 2.0], axis=0).numpy()

1.5

In [82]:
# reshape
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
print(t.shape)

s = tf.constant([[[0, 1, 2], 
                 [3, 4, 5]],
              
                [[6, 7, 8], 
                 [9, 10, 11]]])
print(s.shape)

(2, 2, 3)
(2, 2, 3)


In [83]:
print(tf.reshape(t, shape=[-1, 3]).numpy())
print()
print(tf.reshape(s, shape=[-1, 3]).numpy())
# t, s 중 어떤 걸 쓰나 결과는 같음

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [98]:
p = tf.reshape(t, shape=[-1, 1, 1, 1, 3])
print(p)
p.shape

tf.Tensor(
[[[[[ 0  1  2]]]]



 [[[[ 3  4  5]]]]



 [[[[ 6  7  8]]]]



 [[[[ 9 10 11]]]]], shape=(4, 1, 1, 1, 3), dtype=int32)


TensorShape([4, 1, 1, 1, 3])

In [101]:
q = tf.squeeze(p) # 여러 겹이 있어도 다 없애주는 듯
print(q)

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)


In [152]:
q0 = tf.expand_dims(q, 0)
q1 = tf.expand_dims(q, 1)
q2 = tf.expand_dims(q, 2)
# q3 = tf.expand_dims(q, 3) # 3번부터는 에러 뜸

q11 = tf.expand_dims(q1, 1)

In [153]:
print('q0:\n', q0.numpy(), '\n')
print('q1:\n', q1.numpy(), '\n')
print('q2:\n', q2.numpy(), '\n')
print('q11:\n', q11.numpy(), '\n')

q0:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]] 

q1:
 [[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]] 

q2:
 [[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]] 

q11:
 [[[[ 0  1  2]]]


 [[[ 3  4  5]]]


 [[[ 6  7  8]]]


 [[[ 9 10 11]]]] 



In [155]:
print('q:', q.shape)
print('q0:', q0.shape)
print('q1:', q1.shape)
print('q2:', q2.shape)
print('q11:', q11.shape)

# tf.expand_dims의 정확한 작동방식:
# 함수 한 번 실행하면 rank는 1개 늘어남
# index값: 1을 어디에 삽입하느냐를 나타냄

q: (4, 3)
q0: (1, 4, 3)
q1: (4, 1, 3)
q2: (4, 3, 1)
q11: (4, 1, 1, 3)


In [196]:
# casting
c = tf.cast([True, False, 1 == 1, 0 == 1], tf.int32)
c

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 1, 0])>

In [197]:
# stack
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x,y,z])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [200]:
tf.stack([x,y,z], axis=0)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [201]:
tf.stack([x,y,z], axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [205]:
# ones and zeros like
x = [[0,1,2],[2,1,0]]
tf.ones_like(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [207]:
tf.zeros_like(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>