In [3]:
# Softmax Classifier
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

nb_classes = 3

In [4]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))  
# use_bias is True, by default
# use_bias: Boolean, whether the layer uses a bias vector

# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
tf.model.add(tf.keras.layers.Activation('softmax'))

# use loss == categorical_crossentropy
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=2000)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2000
1/1 [==============================] - 0s 677us/step - loss: 3.5725 - accuracy: 0.3750
Epoch 2/2000
1/1 [==============================] - 0s 2ms/step - loss: 2.4265 - accuracy: 0.3750
Epoch 3/2000
1/1 [==============================] - 0s 996us/step - loss: 1.5531 - accuracy: 0.2500
Epoch 4/2000
1/1 [==============================] - 0s 910us/step - loss: 1.4074 - accuracy: 0.5000
Epoch 5/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.2524 - accuracy: 0.3750
Epoch 6/2000
1/1 [========

1/1 [==============================] - 0s 997us/step - loss: 0.6050 - accuracy: 0.6250
Epoch 158/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6597 - accuracy: 0.7500
Epoch 159/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.6032 - accuracy: 0.6250
Epoch 160/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6581 - accuracy: 0.7500
Epoch 161/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6015 - accuracy: 0.6250
Epoch 162/2000
1/1 [==============================] - 0s 0s/step - loss: 0.6566 - accuracy: 0.7500
Epoch 163/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5998 - accuracy: 0.6250
Epoch 164/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6551 - accuracy: 0.7500
Epoch 165/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5982 - accuracy: 0.6250
Epoch 166/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6535 - accuracy: 0.7500
E

1/1 [==============================] - 0s 2ms/step - loss: 0.5610 - accuracy: 0.7500
Epoch 319/2000
1/1 [==============================] - 0s 995us/step - loss: 0.5050 - accuracy: 0.7500
Epoch 320/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5599 - accuracy: 0.7500
Epoch 321/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5040 - accuracy: 0.7500
Epoch 322/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5589 - accuracy: 0.7500
Epoch 323/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5031 - accuracy: 0.7500
Epoch 324/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5578 - accuracy: 0.7500
Epoch 325/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5021 - accuracy: 0.7500
Epoch 326/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5568 - accuracy: 0.7500
Epoch 327/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5012 - accuracy: 0.7500
Epoc

1/1 [==============================] - 0s 2ms/step - loss: 0.4818 - accuracy: 0.8750
Epoch 479/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4368 - accuracy: 0.7500
Epoch 480/2000
1/1 [==============================] - 0s 996us/step - loss: 0.4809 - accuracy: 0.8750
Epoch 481/2000
1/1 [==============================] - 0s 983us/step - loss: 0.4360 - accuracy: 0.7500
Epoch 482/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4799 - accuracy: 0.8750
Epoch 483/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4353 - accuracy: 0.7500
Epoch 484/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4790 - accuracy: 0.8750
Epoch 485/2000
1/1 [==============================] - 0s 995us/step - loss: 0.4345 - accuracy: 0.7500
Epoch 486/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4780 - accuracy: 0.8750
Epoch 487/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4337 - accuracy: 0.7500
Epo

Epoch 559/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4066 - accuracy: 0.7500
Epoch 560/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4434 - accuracy: 0.8750
Epoch 561/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4059 - accuracy: 0.7500
Epoch 562/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4425 - accuracy: 0.8750
Epoch 563/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4051 - accuracy: 0.7500
Epoch 564/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4415 - accuracy: 0.8750
Epoch 565/2000
1/1 [==============================] - 0s 992us/step - loss: 0.4044 - accuracy: 0.7500
Epoch 566/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4406 - accuracy: 0.8750
Epoch 567/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4037 - accuracy: 0.7500
Epoch 568/2000
1/1 [==============================] - 0s 999us/step - loss: 0.4397 - accura

Epoch 720/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3698 - accuracy: 0.8750
Epoch 721/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3483 - accuracy: 0.8750
Epoch 722/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3688 - accuracy: 0.8750
Epoch 723/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3476 - accuracy: 0.8750
Epoch 724/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3679 - accuracy: 0.8750
Epoch 725/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3469 - accuracy: 0.8750
Epoch 726/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3670 - accuracy: 0.8750
Epoch 727/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3462 - accuracy: 0.8750
Epoch 728/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3661 - accuracy: 0.8750
Epoch 729/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3454 - accu

1/1 [==============================] - 0s 998us/step - loss: 0.2971 - accuracy: 0.8750
Epoch 881/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2905 - accuracy: 0.8750
Epoch 882/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2962 - accuracy: 0.8750
Epoch 883/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2897 - accuracy: 0.8750
Epoch 884/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2953 - accuracy: 0.8750
Epoch 885/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2890 - accuracy: 0.8750
Epoch 886/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2945 - accuracy: 0.8750
Epoch 887/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2883 - accuracy: 1.0000
Epoch 888/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2936 - accuracy: 0.8750
Epoch 889/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2875 - accuracy: 1.0000
Epoc

1/1 [==============================] - 0s 997us/step - loss: 0.2617 - accuracy: 1.0000
Epoch 962/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2627 - accuracy: 0.8750
Epoch 963/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2610 - accuracy: 1.0000
Epoch 964/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2620 - accuracy: 0.8750
Epoch 965/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2604 - accuracy: 1.0000
Epoch 966/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.2612 - accuracy: 0.8750
Epoch 967/2000
1/1 [==============================] - 0s 780us/step - loss: 0.2597 - accuracy: 1.0000
Epoch 968/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2605 - accuracy: 1.0000
Epoch 969/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.2591 - accuracy: 1.0000
Epoch 970/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2598 - accuracy: 1.0000
Epoch

1/1 [==============================] - 0s 997us/step - loss: 0.2311 - accuracy: 1.0000
Epoch 1121/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2310 - accuracy: 1.0000
Epoch 1122/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2308 - accuracy: 1.0000
Epoch 1123/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2307 - accuracy: 1.0000
Epoch 1124/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2306 - accuracy: 1.0000
Epoch 1125/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2305 - accuracy: 1.0000
Epoch 1126/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2304 - accuracy: 1.0000
Epoch 1127/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2303 - accuracy: 1.0000
Epoch 1128/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2301 - accuracy: 1.0000
Epoch 1129/2000
1/1 [==============================] - 0s 990us/step - loss: 0.2300 - accurac

1/1 [==============================] - 0s 997us/step - loss: 0.2137 - accuracy: 1.0000
Epoch 1281/2000
1/1 [==============================] - ETA: 0s - loss: 0.2136 - accuracy: 1.00 - 0s 997us/step - loss: 0.2136 - accuracy: 1.0000
Epoch 1282/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2135 - accuracy: 1.0000
Epoch 1283/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2134 - accuracy: 1.0000
Epoch 1284/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2133 - accuracy: 1.0000
Epoch 1285/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2132 - accuracy: 1.0000
Epoch 1286/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2131 - accuracy: 1.0000
Epoch 1287/2000
1/1 [==============================] - ETA: 0s - loss: 0.2130 - accuracy: 1.00 - 0s 998us/step - loss: 0.2130 - accuracy: 1.0000
Epoch 1288/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2129 - accuracy: 1.0000
Epoch 128

Epoch 1439/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1988 - accuracy: 1.0000
Epoch 1440/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.1988 - accuracy: 1.0000
Epoch 1441/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1987 - accuracy: 1.0000
Epoch 1442/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1986 - accuracy: 1.0000
Epoch 1443/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1985 - accuracy: 1.0000
Epoch 1444/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1984 - accuracy: 1.0000
Epoch 1445/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1983 - accuracy: 1.0000
Epoch 1446/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1982 - accuracy: 1.0000
Epoch 1447/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1982 - accuracy: 1.0000
Epoch 1448/2000
1/1 [==============================] - 0s 998us/step - loss: 0.198

1/1 [==============================] - 0s 3ms/step - loss: 0.1857 - accuracy: 1.0000
Epoch 1600/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1857 - accuracy: 1.0000
Epoch 1601/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1856 - accuracy: 1.0000
Epoch 1602/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1855 - accuracy: 1.0000
Epoch 1603/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1854 - accuracy: 1.0000
Epoch 1604/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1854 - accuracy: 1.0000
Epoch 1605/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1853 - accuracy: 1.0000
Epoch 1606/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1852 - accuracy: 1.0000
Epoch 1607/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1851 - accuracy: 1.0000
Epoch 1608/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1851 - accuracy: 1.0000


1/1 [==============================] - 0s 998us/step - loss: 0.1798 - accuracy: 1.0000
Epoch 1680/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1797 - accuracy: 1.0000
Epoch 1681/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1797 - accuracy: 1.0000
Epoch 1682/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1796 - accuracy: 1.0000
Epoch 1683/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1795 - accuracy: 1.0000
Epoch 1684/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1794 - accuracy: 1.0000
Epoch 1685/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1794 - accuracy: 1.0000
Epoch 1686/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1793 - accuracy: 1.0000
Epoch 1687/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1792 - accuracy: 1.0000
Epoch 1688/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1791 - accuracy:

1/1 [==============================] - 0s 3ms/step - loss: 0.1689 - accuracy: 1.0000
Epoch 1840/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1689 - accuracy: 1.0000
Epoch 1841/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1688 - accuracy: 1.0000
Epoch 1842/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1687 - accuracy: 1.0000
Epoch 1843/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1687 - accuracy: 1.0000
Epoch 1844/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1686 - accuracy: 1.0000
Epoch 1845/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1685 - accuracy: 1.0000
Epoch 1846/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1685 - accuracy: 1.0000
Epoch 1847/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1684 - accuracy: 1.0000
Epoch 1848/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1684 - accuracy: 1.0000


1/1 [==============================] - 0s 997us/step - loss: 0.1593 - accuracy: 1.0000
Epoch 2000/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1592 - accuracy: 1.0000


In [14]:
# Testing & One-hot encoding
print('--------------')
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

print('--------------')
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

print('--------------')
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = tf.model.predict_classes(np.array([[1, 1, 0, 1]]))
print(c, c_onehot)

--------------
[[8.5772360e-03 9.9141252e-01 1.0267441e-05]] [1]
--------------
[[0.82031024 0.16153128 0.01815851]] [0]
--------------
[[1.6131214e-08 3.7664414e-04 9.9962330e-01]] [2]


In [15]:
print('--------------')
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
all_onehot = tf.model.predict_classes(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
print(all)
print(all_onehot)

--------------
[[8.5772276e-03 9.9141252e-01 1.0267432e-05]
 [8.2031012e-01 1.6153137e-01 1.8158503e-02]
 [1.6131244e-08 3.7664417e-04 9.9962330e-01]]
[1 0 2]


In [17]:
# zoo_classifier

# Predicting animal type based on various features
xy = np.loadtxt('csv\data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

nb_classes = 7  # 0 ~ 6

(101, 16) (101, 1)


In [21]:
# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:")
print(y_one_hot)

one_hot:
[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1.

In [24]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()
# param 119개

history = tf.model.fit(x_data, y_one_hot, epochs=1000)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 7)                 119       
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
4/4 [==============================] - 0s 748us/step - loss: 2.1814 - accuracy: 0.1485
Epoch 2/1000
4/4 [==============================] - 0s 997us/step - loss: 1.6694 - accuracy: 0.5248
Epoch 3/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.4828 - accuracy: 0.5644
Epoch 4/1000
4/4 [==============================] - 0s 997us/step - loss: 1.3157 - accuracy: 0.5644
Epoch 5/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.1696 - accuracy: 0.6040
Epoch 6/1000
4/4 [==============================] - 0s 1ms/step - loss: 1.0758 - accuracy: 0.7426
Epoch 7/1000
4/4 [==============================] - 0s 1

4/4 [==============================] - 0s 1ms/step - loss: 0.1456 - accuracy: 0.9802
Epoch 160/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1461 - accuracy: 0.9802
Epoch 161/1000
4/4 [==============================] - 0s 996us/step - loss: 0.1447 - accuracy: 0.9802
Epoch 162/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1436 - accuracy: 0.9802
Epoch 163/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1453 - accuracy: 0.9802
Epoch 164/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1425 - accuracy: 0.9802
Epoch 165/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1453 - accuracy: 0.9802
Epoch 166/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1400 - accuracy: 0.9802
Epoch 167/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1398 - accuracy: 0.9802
Epoch 168/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1399 - accuracy: 0.9802
Epoch 1

4/4 [==============================] - 0s 1ms/step - loss: 0.0812 - accuracy: 1.0000
Epoch 321/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0807 - accuracy: 1.0000
Epoch 322/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0814 - accuracy: 1.0000
Epoch 323/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0803 - accuracy: 1.0000
Epoch 324/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0799 - accuracy: 1.0000
Epoch 325/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0798 - accuracy: 1.0000
Epoch 326/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0794 - accuracy: 1.0000
Epoch 327/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0791 - accuracy: 1.0000
Epoch 328/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0799 - accuracy: 1.0000
Epoch 329/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0789 - accuracy: 1.0000
Epo

Epoch 401/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0661 - accuracy: 1.0000
Epoch 402/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0676 - accuracy: 1.0000
Epoch 403/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0666 - accuracy: 1.0000
Epoch 404/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0662 - accuracy: 1.0000
Epoch 405/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0660 - accuracy: 1.0000
Epoch 406/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0665 - accuracy: 1.0000
Epoch 407/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0658 - accuracy: 1.0000
Epoch 408/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0660 - accuracy: 1.0000
Epoch 409/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0652 - accuracy: 1.0000
Epoch 410/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0650 - accur

Epoch 482/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0560 - accuracy: 1.0000
Epoch 483/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0558 - accuracy: 1.0000
Epoch 484/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0562 - accuracy: 1.0000
Epoch 485/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0557 - accuracy: 1.0000
Epoch 486/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0554 - accuracy: 1.0000
Epoch 487/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0554 - accuracy: 1.0000
Epoch 488/1000
4/4 [==============================] - 0s 996us/step - loss: 0.0553 - accuracy: 1.0000
Epoch 489/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0556 - accuracy: 1.0000
Epoch 490/1000
4/4 [==============================] - 0s 747us/step - loss: 0.0552 - accuracy: 1.0000
Epoch 491/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0554 - acc

4/4 [==============================] - 0s 748us/step - loss: 0.0485 - accuracy: 1.0000
Epoch 564/1000
4/4 [==============================] - 0s 842us/step - loss: 0.0487 - accuracy: 1.0000
Epoch 565/1000
4/4 [==============================] - 0s 683us/step - loss: 0.0484 - accuracy: 1.0000
Epoch 566/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0483 - accuracy: 1.0000
Epoch 567/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0486 - accuracy: 1.0000
Epoch 568/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0479 - accuracy: 1.0000
Epoch 569/1000
4/4 [==============================] - 0s 851us/step - loss: 0.0481 - accuracy: 1.0000
Epoch 570/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0489 - accuracy: 1.0000
Epoch 571/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0479 - accuracy: 1.0000
Epoch 572/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0478 - accuracy: 1.0000
Epo

4/4 [==============================] - 0s 748us/step - loss: 0.0429 - accuracy: 1.0000
Epoch 645/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0435 - accuracy: 1.0000
Epoch 646/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0434 - accuracy: 1.0000
Epoch 647/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0426 - accuracy: 1.0000
Epoch 648/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0425 - accuracy: 1.0000
Epoch 649/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0427 - accuracy: 1.0000
Epoch 650/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0424 - accuracy: 1.0000
Epoch 651/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0423 - accuracy: 1.0000
Epoch 652/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0427 - accuracy: 1.0000
Epoch 653/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0421 - accuracy: 1.

4/4 [==============================] - 0s 997us/step - loss: 0.0382 - accuracy: 1.0000
Epoch 726/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0384 - accuracy: 1.0000
Epoch 727/1000
4/4 [==============================] - 0s 747us/step - loss: 0.0383 - accuracy: 1.0000
Epoch 728/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0388 - accuracy: 1.0000
Epoch 729/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0383 - accuracy: 1.0000
Epoch 730/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0382 - accuracy: 1.0000
Epoch 731/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0387 - accuracy: 1.0000
Epoch 732/1000
4/4 [==============================] - 0s 615us/step - loss: 0.0383 - accuracy: 1.0000
Epoch 733/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0379 - accuracy: 1.0000
Epoch 734/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0379 - accuracy: 1.0000
Epoch

4/4 [==============================] - 0s 1ms/step - loss: 0.0347 - accuracy: 1.0000
Epoch 807/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0347 - accuracy: 1.0000
Epoch 808/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0348 - accuracy: 1.0000
Epoch 809/1000
4/4 [==============================] - 0s 921us/step - loss: 0.0347 - accuracy: 1.0000
Epoch 810/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0353 - accuracy: 1.0000
Epoch 811/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0350 - accuracy: 1.0000
Epoch 812/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0346 - accuracy: 1.0000
Epoch 813/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0346 - accuracy: 1.0000
Epoch 814/1000
4/4 [==============================] - 0s 999us/step - loss: 0.0344 - accuracy: 1.0000
Epoch 815/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0345 - accuracy: 1.0000
Epo

4/4 [==============================] - 0s 748us/step - loss: 0.0292 - accuracy: 1.0000
Epoch 969/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0293 - accuracy: 1.0000
Epoch 970/1000
4/4 [==============================] - ETA: 0s - loss: 0.0261 - accuracy: 1.00 - 0s 496us/step - loss: 0.0293 - accuracy: 1.0000
Epoch 971/1000
4/4 [==============================] - 0s 872us/step - loss: 0.0291 - accuracy: 1.0000
Epoch 972/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0290 - accuracy: 1.0000
Epoch 973/1000
4/4 [==============================] - 0s 918us/step - loss: 0.0291 - accuracy: 1.0000
Epoch 974/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0290 - accuracy: 1.0000
Epoch 975/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0290 - accuracy: 1.0000
Epoch 976/1000
4/4 [==============================] - 0s 984us/step - loss: 0.0289 - accuracy: 1.0000
Epoch 977/1000
4/4 [==============================] - 0s 

In [25]:
# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) # expected prediction == 3
print(tf.model.predict(test_data), tf.model.predict_classes(test_data))

[[8.1482326e-04 1.1750006e-03 5.4861959e-03 9.8743290e-01 3.7554216e-03
  4.7574085e-07 1.3350559e-03]] [3]


In [37]:
# Full x_data test
pred = tf.model.predict_classes(x_data)
for p, y in zip(pred, y_data.flatten()):
    print("[{}]    Prediction: {}    True Y: {}".format(p == int(y), p, int(y)))

[True]    Prediction: 0    True Y: 0
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 3    True Y: 3
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 3    True Y: 3
[True]    Prediction: 3    True Y: 3
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 1    True Y: 1
[True]    Prediction: 3    True Y: 3
[True]    Prediction: 6    True Y: 6
[True]    Prediction: 6    True Y: 6
[True]    Prediction: 6    True Y: 6
[True]    Prediction: 1    True Y: 1
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 3    True Y: 3
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 1    True Y: 1
[True]    Prediction: 1    True Y: 1
[True]    Prediction: 0    True Y: 0
[True]    Prediction: 1    True Y: 1
[True]    Prediction: 5    True Y: 5
[True]    Prediction: 4    True Y: 4
[True]    Prediction: 4    True Y: 4
[